version: '3'
services:
  postgresql:
    image: postgres:12-alpine
    container_name: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=demo
    ports:
      - 5432:5432
