###

GET http://localhost:8080/properties
Accept: application/json

###

PUT http://localhost:8080/properties/demo
Content-Type: application/json
Accept: application/json

{
  "text": "{{$randomInt}}",
  "num": {{$randomInt}}
}

###

GET http://localhost:8080/demo-client/default
Accept: application/json

###

GET http://localhost:8080/demo-client/local
Accept: application/json

###

GET http://localhost:8081/config-service/actuator
Accept: application/json

###

GET http://localhost:8081/config-service/actuator/health
Accept: application/json

###

POST http://localhost:8081/config-service/actuator/bus-refresh/demo-client:**
Accept: application/json

###

POST http://localhost:8080/monitor
Accept: application/json
Content-Type: application/json

{
  "path": "demo-client"
}

###
