info:
  component: Config Server

management:
  endpoints:
#    enabled-by-default: true
    web:
      exposure:
        include:
          - refresh
          - bus-refresh
          - health
          - info
          - prometheus
  server:
    servlet:
      context-path: /^project.name^

spring:
  application:
    name: ^project.name^

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#  cloud:
#    bus:
#      enabled: true
#      refresh:
#        enabled: true

#    config:
#      server:
#        native:
#          order: 0
#        jdbc:
#          order: 1

  flyway:
    clean-on-validation-error: true

  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20
          fetch_size: 20
          batch_versioned_data: true
    hibernate:
      ddl-auto: validate

  main:
    banner-mode: off

  autoconfigure:
    exclude: com.integralblue.log4jdbc.spring.Log4jdbcAutoConfiguration

server:
  forward-headers-strategy: framework
  shutdown: graceful

logging:
  level:
    io.github.cepr0: debug
    org.springframework:
      security: debug
      web: debug
      cloud: debug
      messaging: debug
    jdbc:
      sqltiming: info
      resultsettable: info
      sqlonly: fatal
      audit: fatal
      resultset: fatal
      connection: fatal

log4jdbc:
  dump.sql:
    addsemicolon: true
    maxlinelength: 0
  trim.sql:
    extrablanklines: false
