logging:
  level:
    io.github.cepr0: debug
    org.springframework:
      security: debug
      web: debug
      cloud: debug
    jdbc:
      sqltiming: info
      resultsettable: info
      sqlonly: fatal
      audit: fatal
      resultset: fatal
      connection: fatal

log4jdbc:
  dump.sql:
    addsemicolon: true
    maxlinelength: 0
  trim.sql:
    extrablanklines: false

spring:
  autoconfigure:
    exclude: com.integralblue.log4jdbc.spring.Log4jdbcAutoConfiguration
