###

GET http://localhost:8090/demo
Accept: application/json

###

GET http://localhost:8091/demo-client/actuator
Accept: application/json

###

POST http://localhost:8091/demo-client/actuator/refresh
Content-Type: application/json

###

GET http://localhost:8091/demo-client/actuator/health
Accept: application/json

###

