info:
  component: Config Client

management:
  endpoints:
#    enabled-by-default: true
    web:
      exposure:
        include: "*"
#          - refresh
#          - bus-refresh
#          - health
#          - info
#          - prometheus
  server:
    servlet:
      context-path: /demo-client

spring:
  application:
    name: demo-client

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
  main:
    banner-mode: off

server:
  forward-headers-strategy: framework
  shutdown: graceful

logging:
  level:
    io.github.cepr0: debug
    org.springframework:
      security: debug
      web: debug
      cloud: debug
